name = "freebot"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "telegram-projects"
database_id = "YOUR_D1_DATABASE_ID_HERE"

[vars]
STORAGE_QUOTA_BYTES = 419430400 # 400MB
