// src/utils/pdfTemplate.js
// Generates an HTML document with a floating "Download PDF" button.
// The button triggers window.print() which lets mobile users "Save as PDF".

export function generatePdfHtml(title, contentHtml) {
  return `<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  body {
    font-family: Georgia, 'Times New Roman', serif;
    max-width: 800px;
    margin: 0 auto;
    padding: 24px 16px 80px;
    line-height: 1.7;
    color: #222;
    background: #fff;
  }
  h1 { font-size: 1.6em; margin-bottom: 0.5em; border-bottom: 2px solid #333; padding-bottom: 8px; }
  h2 { font-size: 1.3em; margin-top: 1.5em; }
  h3 { font-size: 1.1em; margin-top: 1.2em; }
  p { margin: 0.6em 0; text-align: justify; }
  table { width: 100%; border-collapse: collapse; margin: 1em 0; font-size: 0.95em; }
  th, td { border: 1px solid #999; padding: 8px 10px; text-align: left; }
  th { background: #f0f0f0; font-weight: bold; }
  tr:nth-child(even) { background: #fafafa; }
  pre { background: #f5f5f5; padding: 12px; border-radius: 4px; overflow-x: auto; font-size: 0.9em; }
  code { background: #f0f0f0; padding: 2px 5px; border-radius: 3px; font-size: 0.9em; }
  pre code { background: none; padding: 0; }
  blockquote { border-left: 4px solid #4CAF50; margin: 1em 0; padding: 8px 16px; background: #f9fff9; color: #555; }
  ul, ol { padding-left: 1.5em; }
  li { margin: 0.3em 0; }
  .download-btn {
    position: fixed;
    bottom: 24px;
    right: 24px;
    background: #4CAF50;
    color: #fff;
    border: none;
    padding: 14px 28px;
    border-radius: 30px;
    font-size: 16px;
    font-weight: bold;
    box-shadow: 0 4px 16px rgba(0,0,0,0.3);
    z-index: 99999;
    cursor: pointer;
    transition: transform 0.15s, box-shadow 0.15s;
  }
  .download-btn:active {
    transform: scale(0.95);
    box-shadow: 0 2px 8px rgba(0,0,0,0.3);
  }
  .footer {
    margin-top: 3em;
    padding-top: 1em;
    border-top: 1px solid #ddd;
    font-size: 0.85em;
    color: #999;
    text-align: center;
  }
  @media print {
    .download-btn { display: none !important; }
    body { padding-bottom: 0; }
    a { color: #000; text-decoration: underline; }
  }
  @media (max-width: 600px) {
    body { padding: 16px 12px 80px; }
    .download-btn { bottom: 16px; right: 16px; padding: 12px 22px; font-size: 14px; }
  }
</style>
</head>
<body>
<h1>${escapeHtml(title)}</h1>
${contentHtml}
<div class="footer">Generated by My Assist</div>
<button class="download-btn" onclick="window.print()">&#11015; Download PDF</button>
</body>
</html>`;
}

function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
