// src/github.js
// All GitHub REST API interactions: token validation, repo creation,
// pushing/committing files, reading/listing repo contents.

export async function validateGithubToken(pat) {
  try {
    const res = await fetch("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${pat}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "telegram-ai-bot"
      }
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data?.login || null;
  } catch {
    return null;
  }
}

export async function createGithubRepo(pat, name) {
  const res = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${pat}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "User-Agent": "telegram-ai-bot"
    },
    body: JSON.stringify({
      name,
      description: "Generated by telegram-ai-bot",
      private: true,
      auto_init: true,
      has_wiki: false
    })
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.message || `GitHub create repo error: ${res.status}`);
  return data;
}

export async function pushFilesToGithub(pat, fullName, files) {
  const headers = {
    Authorization: `Bearer ${pat}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "User-Agent": "telegram-ai-bot"
  };
  const base = `https://api.github.com/repos/${fullName}`;

  const blobs = [];
  for (const f of files) {
    const r = await fetch(`${base}/git/blobs`, {
      method: "POST",
      headers,
      body: JSON.stringify({ content: f.content, encoding: "utf-8" })
    });
    const b = await r.json();
    if (!r.ok) throw new Error(b?.message || "git blob error");
    blobs.push({ path: f.path, mode: "100644", type: "blob", sha: b.sha });
  }

  const treeRes = await fetch(`${base}/git/trees`, {
    method: "POST",
    headers,
    body: JSON.stringify({ tree: blobs })
  });
  const tree = await treeRes.json();
  if (!treeRes.ok) throw new Error(tree?.message || "git tree error");

  const commitRes = await fetch(`${base}/git/commits`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      message: "Initial scaffold via telegram-ai-bot",
      tree: tree.sha,
      parents: []
    })
  });
  const commit = await commitRes.json();
  if (!commitRes.ok) throw new Error(commit?.message || "git commit error");

  const refRes = await fetch(`${base}/git/refs`, {
    method: "POST",
    headers,
    body: JSON.stringify({ ref: "refs/heads/main", sha: commit.sha })
  });
  return refRes.ok;
}

export async function commitToRepo(pat, fullName, message, files, branch = "main") {
  const headers = {
    Authorization: `Bearer ${pat}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "User-Agent": "telegram-ai-bot"
  };
  const base = `https://api.github.com/repos/${fullName}`;

  const refRes = await fetch(`${base}/git/refs/heads/${branch}`, { headers });
  let parentSha = "";
  let treeBase = null;
  if (refRes.ok) {
    const refData = await refRes.json();
    parentSha = refData?.object?.sha || "";
    // GitHub ref API doesn't return tree_sha — fetch the commit to get it
    if (parentSha) {
      const commitRes = await fetch(`${base}/git/commits/${parentSha}`, { headers });
      if (commitRes.ok) {
        const commitData = await commitRes.json();
        treeBase = commitData?.tree?.sha || null;
      }
    }
  }

  const blobs = [];
  for (const f of files) {
    const r = await fetch(`${base}/git/blobs`, {
      method: "POST",
      headers,
      body: JSON.stringify({ content: f.content, encoding: "utf-8" })
    });
    const b = await r.json();
    if (!r.ok) throw new Error(b?.message || "git blob error");
    blobs.push({ path: f.path, mode: "100644", type: "blob", sha: b.sha });
  }

  const treeBody = treeBase ? { tree: blobs, base_tree: treeBase } : { tree: blobs };
  const treeRes = await fetch(`${base}/git/trees`, {
    method: "POST",
    headers,
    body: JSON.stringify(treeBody)
  });
  const tree = await treeRes.json();
  if (!treeRes.ok) throw new Error(tree?.message || "git tree error");

  const commitRes = await fetch(`${base}/git/commits`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      message,
      tree: tree.sha,
      parents: parentSha ? [parentSha] : []
    })
  });
  const commit = await commitRes.json();
  if (!commitRes.ok) throw new Error(commit?.message || "git commit error");

  const updateRes = await fetch(`${base}/git/refs/heads/${branch}`, {
    method: "PATCH",
    headers,
    body: JSON.stringify({ sha: commit.sha, force: false })
  });
  if (!updateRes.ok) {
    const errData = await updateRes.json().catch(() => ({}));
    throw new Error(errData?.message || "git update ref error");
  }
}

export async function listRepoContents(pat, repo, folderPath) {
  if (!folderPath) folderPath = "";
  const url = folderPath
    ? `https://api.github.com/repos/${repo}/contents/${encodeURIComponent(folderPath)}`
    : `https://api.github.com/repos/${repo}/contents`;
  try {
    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${pat}`, Accept: "application/vnd.github+json", "User-Agent": "telegram-ai-bot" }
    });
    if (!res.ok) return null;
    const data = await res.json();
    if (!Array.isArray(data)) return null;
    return data.map((f) => ({
      path: f.path,
      type: f.type || "file",
      size: f.size || 0
    }));
  } catch {
    return null;
  }
}

export async function readRepoFile(pat, repo, filePath) {
  try {
    const res = await fetch(`https://api.github.com/repos/${repo}/contents/${encodeURIComponent(filePath)}`, {
      headers: { Authorization: `Bearer ${pat}`, Accept: "application/vnd.github+json", "User-Agent": "telegram-ai-bot" }
    });
    if (!res.ok) return null;
    const data = await res.json();
    if (!data?.content) return null;
    return atob(data.content.replace(/\s/g, ""));
  } catch {
    return null;
  }
}
